FROM python:3.11-slim

LABEL version="0.0.1"

RUN pip install --no-cache-dir \
    biopython \
    matplotlib \
    numpy \
    pandas \
    pysam \
    regex \
    scikit-learn \
    scipy \
    seaborn \
    click

WORKDIR /workspace
